[package]
name = "neuron_controller_canister"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
candid_gen = { path = "../../../libraries/candid_gen" }
human_readable = { path = "../../../libraries/human_readable" }
nns_governance_canister = { path = "../../../external_canisters/nns_governance/api" }
serde = { workspace = true }
types = { path = "../../../libraries/types" }
