[package]
name = "local_user_index_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
community_canister = { path = "../../community/api" }
event_store_canister = { workspace = true }
group_canister = { path = "../../group/api" }
ic-ledger-types = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
ts_export = { path = "../../../libraries/ts_export" }
ts-rs = { workspace = true }
types = { path = "../../../libraries/types" }
user_canister = { path = "../../user/api" }
utils = { path = "../../../libraries/utils" }
