[package]
name = "group_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
callback_canister = { path = "../../callback/api" }
callback_canister_c2c_client = { path = "../../callback/c2c_client" }
candid = { workspace = true }
canister_api_macros = { path = "../../../libraries/canister_api_macros" }
canister_logger = { path = "../../../libraries/canister_logger" }
canister_state_macros = { workspace = true }
canister_tracing_macros = { path = "../../../libraries/canister_tracing_macros" }
chat_events = { path = "../../../libraries/chat_events" }
futures = { workspace = true }
group_canister = { path = "../api" }
group_index_canister = { path = "../../group_index/api" }
group_index_canister_c2c_client = { path = "../../group_index/c2c_client" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
msgpack = { path = "../../../libraries/msgpack" }
notifications_canister = { path = "../../notifications/api" }
notifications_canister_c2c_client = { path = "../../notifications/c2c_client" }
open_storage_bucket_client = { path = "../../../libraries/open_storage_bucket_client" }
rand = { workspace = true }
regex = { workspace = true }
search = { path = "../../../libraries/search" }
serde = { workspace = true }
serde_bytes = { workspace = true }
stable_memory = { workspace = true }
tracing = { workspace = true }
types = { path = "../../../libraries/types" }
user_canister = { path = "../../user/api" }
user_canister_c2c_client = { path = "../../user/c2c_client" }
user_index_canister = { path = "../../user_index/api" }
user_index_canister_c2c_client = { path = "../../user_index/c2c_client" }
utils = { path = "../../../libraries/utils", features = ["range-set"] }
