[package]
name = "group_canister_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
canister_client_macros = { path = "../../../libraries/canister_client_macros" }
group_canister = { path = "../api" }
ic-agent = { workspace = true }
types = { path = "../../../libraries/types" }
