[package]
name = "group_index_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.7"
canister_logger = { path = "../../../libraries/canister_logger" }
cycles_utils = { path = "../../../libraries/cycles_utils" }
futures = "0.3.16"
group_canister = { path = "../../group/api" }
group_index_canister = { path = "../api" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
ic-cdk-macros = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
search = { path = "../../../libraries/search" }
serde = "1.0.126"
tracing = "0.1.29"
types = { path = "../../../libraries/types", features = ["compression"] }
utils = { path = "../../../libraries/utils" }
