[package]
name = "group_index_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.4"
group_index_canister = { path = "../api" }
ic-cdk = { version = "0.3.1", default-features = false }
ic-cdk-macros = "0.3.1"
serde = "1.0.126"
shared = { path = "../../../shared" }
types = { path = "../../../types" }