[package]
name = "group_index_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.9"
canister_api_macros = { path = "../../../libraries/canister_api_macros" }
canister_logger = { path = "../../../libraries/canister_logger" }
canister_state_macros = { path = "../../../libraries/canister_state_macros" }
cycles_utils = { path = "../../../libraries/cycles_utils" }
futures = "0.3.16"
group_canister = { path = "../../group/api" }
group_index_canister = { path = "../api" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = "0.3.3"
ic-cdk-macros = "0.3.3"
search = { path = "../../../libraries/search" }
serde = "1.0.126"
serializer = { path = "../../../libraries/serializer" }
tracing = "0.1.29"
types = { path = "../../../libraries/types", features = ["compression"] }
utils = { path = "../../../libraries/utils" }
