[package]
name = "user_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.5"
futures = "0.3.16"
group_canister = { path = "../../group/api" }
group_canister_client = { path = "../../group/client" }
group_index_canister = { path = "../../group_index/api" }
group_index_canister_client = { path = "../../group_index/client" }
ic-cdk = { version = "0.3.1", default-features = false }
ic-cdk-macros = "0.3.1"
itertools = "0.10.1"
log = "0.4.14"
notifications_canister = { path = "../../notifications/api" }
notifications_canister_client = { path = "../../notifications/client" }
serde = "1.0.126"
serde_bytes = "0.11.5"
types = { path = "../../../libraries/types" }
utils = { path = "../../../libraries/utils" }
user_canister = { path = "../api" }
user_canister_client = { path = "../client" }