[package]
name = "user_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.7"
canister_api_macros = { path = "../../../libraries/canister_api_macros" }
canister_logger = { path = "../../../libraries/canister_logger" }
chat_events = { path = "../../../libraries/chat_events" }
cycles_utils = { path = "../../../libraries/cycles_utils" }
futures = "0.3.16"
group_canister = { path = "../../group/api" }
group_canister_c2c_client = { path = "../../group/c2c_client" }
group_index_canister = { path = "../../group_index/api" }
group_index_canister_c2c_client = { path = "../../group_index/c2c_client" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "827d553181aaac61cf6209aa0654baf19b1dbef4" }
ic-cdk-macros = { git = "https://github.com/hpeebles/cdk-rs", rev = "827d553181aaac61cf6209aa0654baf19b1dbef4" }
itertools = "0.10.1"
ledger_utils = { path = "../../../libraries/ledger_utils" }
notifications_canister = { path = "../../notifications/api" }
notifications_canister_c2c_client = { path = "../../notifications/c2c_client" }
search = { path = "../../../libraries/search" }
serde = "1.0.126"
serializer = { path = "../../../libraries/serializer" }
tracing = "0.1.29"
types = { path = "../../../libraries/types" }
utils = { path = "../../../libraries/utils", features = ["range-set"] }
user_canister = { path = "../api" }
user_canister_c2c_client = { path = "../c2c_client" }
user_index_canister = { path = "../../user_index/api" }
user_index_canister_c2c_client = { path = "../../user_index/c2c_client" }
