[package]
name = "shared"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.51"
candid = "0.7.7"
futures = "0.3.16"
garcon = "0.2.3"
ic-agent = "0.6.0"
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
notifications_canister = { path = "../../canisters/notifications/api" }
openssl = { version = "0.10.35", features = ["vendored"] }
serde = "1.0.126"
serde_json = "1.0.64"
tokio = { version = "1.10.0", features = ["macros", "time"] }
tracing = "0.1.29"
types = { path = "../../libraries/types" }
utils = { path = "../../libraries/utils" }
web-push = { git = "https://github.com/pimeys/rust-web-push", rev = "85870ec55badfb95d74d1c7bd354a0deb5193481" }