[package]
name = "ledger_utils"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.10"
futures = "0.3.16"
ic-cdk = "0.5.0"
ic-ledger-types = "0.1.1"
itertools = "0.10.1"
serde = "1.0.126"
serde_bytes = "0.11.5"
serde_cbor = "0.11.2"
sha2 = "0.10.2"
types = { path = "../types" }
utils = { path = "../utils" }
