[package]
name = "ledger_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-ledger-types = { workspace = true }
icp_ledger_canister_c2c_client = { path = "../../external_canisters/icp_ledger/c2c_client" }
icrc_ledger_canister_c2c_client = { path = "../../external_canisters/icrc_ledger/c2c_client" }
icrc-ledger-types = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
types = { path = "../types" }

[dev-dependencies]
test-case = { workspace = true }
