[package]
name = "ledger_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
ic-icrc1 = { workspace = true }
ic-icrc1-client = { workspace = true }
ic-icrc1-client-cdk = { workspace = true }
ic-ledger-types = { workspace = true }
icp_ledger_canister_c2c_client = { path = "../../external_canisters/icp_ledger/c2c_client" }
icrc-ledger-types = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
sha2 = { workspace = true }
sha256 = { path = "../sha256" }
types = { path = "../types" }
