[package]
name = "local_group_index_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
event_store_canister = { workspace = true }
ic-ledger-types = { workspace = true }
serde = { workspace = true }
serde_bytes = "0.11"
types = { path = "../../../libraries/types" }