[package]
name = "group_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.5"
cycles_utils = { path = "../../../libraries/cycles_utils" }
futures = "0.3.16"
group_canister = { path = "../api" }
group_index_canister = { path = "../../group_index/api" }
group_index_canister_c2c_client = { path = "../../group_index/c2c_client" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
ic-cdk-macros = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
log = "0.4.14"
notifications_canister = { path = "../../notifications/api" }
notifications_canister_c2c_client = { path = "../../notifications/c2c_client" }
range-set = "0.0.7"
search = { path = "../../../libraries/search" }
serde = "1.0.126"
serde_bytes = "0.11.5"
types = { path = "../../../libraries/types" }
user_canister = { path = "../../user/api" }
user_canister_c2c_client = { path = "../../user/c2c_client" }
utils = { path = "../../../libraries/utils", features = ["range-set"] }
