[package]
name = "group_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.6.21"
group_canister = { path = "../api" }
ic-cdk = "0.3.0"
ic-cdk-macros = "0.3.0"
group_index_canister = { path = "../../group_index/api" }
notifications_canister = { path = "../../notifications/api" }
serde = "1.0.126"
shared = { path = "../../../shared" }