[package]
name = "notification_service_aws"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.51"
aws-sdk-dynamodb = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.11-alpha", package = "aws-sdk-dynamodb" }
candid = "0.7.4"
lambda_runtime = "0.3.0"
serde = "1.0.126"
shared = { path = "../shared", package = "notification_service_shared" }
tokio = "1.8.1"
