[package]
name = "fire_and_forget_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canister_client = { path = "../canister_client" }
canister_time = { path = "../canister_time" }
constants = { path = "../constants" }
futures = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
tracing = { workspace = true }
types = { path = "../types" }
utils = { path = "../utils" }
