[package]
name = "user_index_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.5"
cycles_utils = { path = "../../../libraries/cycles_utils" }
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
ic-cdk-macros = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
itertools = "0.10.1"
phonenumber = "0.3.1"
serde = "1.0.126"
serde_bytes = "0.11"
types = { path = "../../../libraries/types" }
user_canister = { path = "../../user/api" }
user_index_canister = { path = "../api" }
utils = { path = "../../../libraries/utils" }
