[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
canister_client = { path = "../canister_client" }
cycles_dispenser_client = { path = "../cycles_dispenser_client" }
getrandom = { workspace = true, features = ["custom"] }
ic-cdk = { workspace = true }
itertools = { workspace = true }
msgpack = { path = "../msgpack" }
rand = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha3 = { workspace = true }
tracing = { workspace = true }
types = { path = "../types" }