[package]
name = "utils"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.15"
canister_client_macros = { path = "../canister_client_macros" }
compile-time-run = "0.2.12"
getrandom = { version = "0.2.7", features = ["js", "custom"] }
ic-cdk = "0.5.6"
itertools = "0.10.3"
msgpack = { path = "../msgpack" }
rand = "0.8.5"
range-set = { version = "0.0.9", features = ["serde"], optional = true }
serde = "1.0.137"
serde_bytes = "0.11.6"
tracing = "0.1.33"
types = { path = "../types" }