[package]
name = "http_request"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.14"
canister_logger = { path = "../canister_logger" }
num-traits = "0.2.14"
serde = "1.0.136"
serde_bytes = "0.11.5"
serde_json = "1.0.64"
types = { path = "../types" }
utils = { path = "../utils" }