[package]
name = "sms_service"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

[dependencies]
aws-sdk-dynamodb = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.11-alpha", package = "aws-sdk-dynamodb" }
aws-sdk-sns = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.11-alpha", package = "aws-sdk-sns" }
candid = "0.7.4"
futures = "0.3.16"
garcon = "0.2.3"
ic-agent = "0.6.0"
ic-cdk = { version = "0.3.1", default-features = false }
lambda_runtime = "0.3.0"
openssl = { version = "0.10.35", features = ["vendored"] }
serde = "1.0.126"
shared = { path = "../shared" }
tokio = "1.8.1"
types = { path = "../types" }
user_index_canister = { path = "../canisters/user_index/api" }

[[bin]]
name = "bootstrap"
path = "src/main.rs"