[package]
name = "user_index_canister"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
candid_gen = { path = "../../../libraries/candid_gen" }
human_readable = { path = "../../../libraries/human_readable" }
ic-ledger-types = { workspace = true }
modclub_canister = { path = "../../../external_canisters/modclub/api" }
serde = { workspace = true }
serde_bytes = { workspace = true }
ts_export = { path = "../../../libraries/ts_export" }
ts-rs = { workspace = true }
types = { path = "../../../libraries/types" }
