[package]
name = "online_users_aggregator_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.14"
canister_logger = { path = "../../../libraries/canister_logger" }
canister_state_macros = { git = "https://github.com/open-ic/ic-utils", rev = "c7aa6b402a41b2cf5e67903055f2b809b68469c6" }
canister_tracing_macros = { path = "../../../libraries/canister_tracing_macros" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"
serde = "1.0.136"
stable_memory = { git = "https://github.com/open-ic/ic-utils", rev = "c7aa6b402a41b2cf5e67903055f2b809b68469c6" }
tracing = "0.1.33"
types = { path = "../../../libraries/types", features = ["compression"] }
user_index_canister = { path = "../../user_index/api" }
user_index_canister_c2c_client = { path = "../../user_index/c2c_client" }
online_users_aggregator_canister = { path = "../api" }
utils = { path = "../../../libraries/utils" }
