[package]
name = "group_index_canister_impl"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.14"
canister_api_macros = { path = "../../../libraries/canister_api_macros" }
canister_logger = { path = "../../../libraries/canister_logger" }
canister_state_macros = { git = "https://github.com/open-ic/ic-utils", rev = "c7aa6b402a41b2cf5e67903055f2b809b68469c6" }
futures = "0.3.21"
group_canister = { path = "../../group/api" }
group_canister_c2c_client = { path = "../../group/c2c_client" }
group_index_canister = { path = "../api" }
http_request = { path = "../../../libraries/http_request" }
ic-cdk = "0.5.0"
ic-cdk-macros = "0.5.0"
rand = "0.7.3"
search = { path = "../../../libraries/search" }
serde = "1.0.136"
stable_memory = { git = "https://github.com/open-ic/ic-utils", rev = "c7aa6b402a41b2cf5e67903055f2b809b68469c6" }
tracing = "0.1.33"
types = { path = "../../../libraries/types", features = ["compression"] }
user_canister = { path = "../../user/api" }
user_canister_c2c_client = { path = "../../user/c2c_client" }
utils = { path = "../../../libraries/utils" }
