[package]
name = "human_readable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
hex = { workspace = true }
human_readable_derive = { path = "../human_readable_derive" }
serde = { workspace = true }
serde_json = { workspace = true }
sha256 = { path = "../sha256" }
types = { path = "../types" }