[package]
name = "canister_logger"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.15"
serde = "1.0.137"
tracing = "0.1.33"
tracing-attributes = "0.1.20"
tracing-subscriber = { version = "0.3.11", features = ["json"] }
types = { path = "../types" }
