[package]
name = "p2p"
version = "0.1.0"
authors = ["Hamish Peebles <hamish.peebles@dfinity.org>", "Matt Grogan <matthew.grogan@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.2.4"
ic-cdk-macros = "0.2.4"
serde = "1.0.111"
shared = { path = "../shared", version = "0.1.0" }
