[package]
name = "user_index_canister_client"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = { version = "0.3.1", default-features = false }
log = "0.4.14"
shared = { path = "../../../shared" }
types = { path = "../../../types" }
user_index_canister = { path = "../api" }