[package]
name = "sms_sender_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
candid = { workspace = true }
futures = { workspace = true }
garcon = { workspace = true }
ic-agent = { workspace = true }
index_store = { path = "../../libraries/index_store" }
user_index_canister = { path = "../../canisters/user_index/api" }
openssl = { workspace = true, features = ["vendored"] }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
types = { path = "../../libraries/types" }
