[package]
name = "sms_sender_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
candid = "0.7.14"
futures = "0.3.21"
garcon = "0.2.3"
ic-agent = "0.15.0"
index_store = { path = "../../libraries/index_store" }
user_index_canister = { path = "../../canisters/user_index/api" }
openssl = { version = "0.10.35", features = ["vendored"] }
serde = "1.0.136"
tokio = "1.11.0"
tracing = "0.1.33"
types = { path = "../../libraries/types" }
