[package]
name = "user_index_canister_client"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.17"
canister_client_macros = { path = "../../../libraries/canister_client_macros", features = ["ingress"] }
ic-agent = "0.20.0"
types = { path = "../../../libraries/types" }
user_index_canister = { path = "../api" }
