[package]
name = "sms_sender_cli"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

[dependencies]
aws-config = "0.9.0"
candid = "0.7.17"
dotenv = "0.15.0"
index_store = { path = "../../libraries/index_store" }
sms_sender_aws = { path = "../aws" }
sms_sender_core = { path = "../core" }
tokio = { version = "1.15.0", features = ["macros"] }
tracing = "0.1.33"
tracing-subscriber = "0.3.11"
types = { path = "../../libraries/types" }
