[package]
name = "open_storage_bucket_client"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
ic-cdk = "0.5.1"
open_storage_bucket_canister = { path = "../../canisters/open_storage_bucket/api" }
open_storage_bucket_canister_c2c_client = { path = "../../canisters/open_storage_bucket/c2c_client" }
types = { path = "../types" }