[package]
name = "group_index_canister_client"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.5"
canister_client_macros = { path = "../../../libraries/canister_client_macros", features = ["ingress"] }
group_index_canister = { path = "../api" }
ic-agent = "0.7.0"
log = "0.4.14"
types = { path = "../../../libraries/types" }
