[package]
name = "types"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.14"
ic-ledger-types = "0.1.1"
lzma-rs = { version = "0.2.0", optional = true }
serde = "1.0.136"
serde_bytes = "0.11.5"

[features]
compression = ["lzma-rs"]
