[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
hex = { workspace = true }
ic-ledger-types = { workspace = true }
icrc-ledger-types = { workspace = true }
rand = { workspace = true }
range-set = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2.workspace = true
ts_export = { path = "../ts_export" }
ts-rs.workspace = true