[package]
name = "online_users_aggregator_canister"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.15"
candid_gen = { path = "../../../libraries/candid_gen" }
serde = "1.0.137"
types = { path = "../../../libraries/types" }