[package]
name = "notification_service"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

[dependencies]
aws-sdk-dynamodb = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.11-alpha", package = "aws-sdk-dynamodb" }
candid = "0.6.21"
futures = "0.3.15"
ic-agent = "0.5.2"
ic-cdk = "0.3.0"
lambda_runtime = "0.3.0"
notifications_canister = { path = "../canisters/notifications/api" }
openssl = { version = "0.10.35", features = ["vendored"] }
serde = "1.0.126"
serde_json = "1.0.64"
shared = { path = "../shared" }
tokio = "1.8.1"
web-push = "0.7.2"

[[bin]]
name = "bootstrap"
path = "src/main.rs"