[package]
name = "notification_pusher_aws"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
aws-config = { workspace = true }
candid = { workspace = true }
dotenv = { workspace = true }
dynamodb_index_store = { path = "../../libraries/dynamodb_index_store" }
futures = { workspace = true }
index_store = { path = "../../libraries/index_store" }
notification_pusher_core = { path = "../core" }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
types = { path = "../../libraries/types" }
