[package]
name = "notification_pusher_aws"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.53"
aws-config = "0.9.0"
candid = "0.7.14"
dotenv = "0.15.0"
dynamodb_index_store = { path = "../../libraries/dynamodb_index_store" }
index_store = { path = "../../libraries/index_store" }
notification_pusher_core = { path = "../core" }
serde = "1.0.136"
tokio = { version = "1.10.0", features = ["macros"] }
tracing = "0.1.33"
tracing-subscriber = "0.3.11"
types = { path = "../../libraries/types" }
