[package]
name = "notification_pusher_core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = { workspace = true }
base64 = { workspace = true }
ic-agent = { workspace = true }
index_store = { path = "../../libraries/index_store" }
notifications_canister = { path = "../../canisters/notifications/api" }
notifications_canister_client = { path = "../../canisters/notifications/client" }
notifications_index_canister = { path = "../../canisters/notifications_index/api" }
notifications_index_canister_client = { path = "../../canisters/notifications_index/client" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }
tracing = { workspace = true }
types = { path = "../../libraries/types" }
web-push = { workspace = true }