[package]
name = "callback_canister_c2c_client"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.14"
callback_canister = { path = "../api" }
canister_client_macros = { path = "../../../libraries/canister_client_macros" }
ic-cdk = "0.5.0"
tracing = "0.1.33"
types = { path = "../../../libraries/types" }
