[package]
name = "notification_pusher_cli"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.51"
candid = "0.7.5"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
shared = { path = "../shared" }
tokio = { version = "1.10.0", features = ["macros", "time"] }
