[package]
name = "group_index_canister_c2c_client"
version = "0.1.0"
authors = ["Hamish Peebles <hamishpeebles@gmail.com>", "Matt Grogan <megrogan@gmail.com>", "Julian Jelfs <julian.jelfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canister_client_macros = { path = "../../../libraries/canister_client_macros" }
group_index_canister = { path = "../api" }
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "6f1539aac70aae9ee7f1d2c326c633b6b863721f" }
slog = "2.7.0"
slog-scope = "4.4.0"
types = { path = "../../../libraries/types" }
