[package]
name = "group_chat_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
chat_events = { path = "../chat_events" }
search = { path = "../search" }
serde = { workspace = true }
types = { path = "../types" }
utils = { path = "../utils" }

