[package]
name = "event_relay_canister_c2c_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
canister_client = { path = "../../../libraries/canister_client" }
event_relay_canister = { path = "../api" }
ic-cdk = { workspace = true }
types = { path = "../../../libraries/types" }
