[package]
name = "local_group_index_canister_c2c_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canister_client_macros = { path = "../../../libraries/canister_client_macros" }
ic-cdk = { workspace = true }
msgpack = { path = "../../../libraries/msgpack" }
tracing = { workspace = true }
types = { path = "../../../libraries/types" }
local_group_index_canister = { path = "../api" }
