[package]
name = "notifications_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
notifications_index_canister = { path = "../../notifications_index/api" }
serde = { workspace = true }
serde_bytes = { workspace = true }
ts_export = { path = "../../../libraries/ts_export" }
ts-rs = { workspace = true }
types = { path = "../../../libraries/types" }