[package]
name = "notifications_canister_c2c_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canister_client = { path = "../../../libraries/canister_client" }
ic-cdk = { workspace = true }
msgpack = { path = "../../../libraries/msgpack" }
notifications_canister = { path = "../api" }
tracing = { workspace = true }
types = { path = "../../../libraries/types" }
