name: Deploy frontend

# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - deploy

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    env:
      DFX_VERSION: 0.8.4
      USERGEEK_APIKEY: ${{ secrets.GH_USERGEEK_APIKEY }}
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.GH_ROLLBAR_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - name: Build the frontend
        run: |
          cd frontend
          npm ci
          npm run build:prod_test

      - name: Deploy the frontend to prod test
        id: deploy
        uses: fleekhq/ic-deploy-action@master
        with:
          identity: ${{ secrets.DFX_IDENTITY }}
          wallets: ${{ secrets.DFX_WALLETS }}
          dfx_params: website
          network: ic_test
