[package]
name = "shared"
version = "0.1.0"
authors = ["Hamish Peebles <hamish.peebles@dfinity.org>", "Matt Grogan <matthew.grogan@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.6.21"
ic-cdk = "0.2.4"
ic-types = "0.1.2"
log = "0.4.14"
serde = "1.0.126"
serde_bytes = "0.11.5"
